### ISSUE TITLE
About hp, mp, tp interface ui adjustment problem

### ISSUE THREAD

**Issue by dds763** [KageDesu/Alpha-ABS-Z#1]
I recently found some problems in the process of debugging absz, because my game is 1920 * 1080 resolution, 
so I need to adjust the location of the ui, but hp, mp, tp bar in addition to the ui editing interface can be adjusted ,
I did not find other methods of adjustment, between the ui editing interface can not be saved to the project, 
so I raised this question, there is no way to adjust the ui?

**Comment by KageDesu** [comment]
AABSZ is still Beta, it's why right now plugin not have UI customization. I already implemented plugin parameters for modify all UI elements. Please wait next update, will be in April.

**Comment by dds763** [comment]
> AABSZ is still Beta, it's why right now plugin not have UI customization. I already implemented plugin parameters for modify all UI elements. Please wait next update, will be in April.

Thank you, I understand the situation, and look forward to your next update
