### ISSUE TITLE
uAPI.executeAASkillOnChar does not work with skills that have speed != 0

### ISSUE THREAD

**Issue by donaldderrick** [KageDesu/Alpha-ABS-Z#2]
Hi KageDesu,

I've been on your patreon since the beginning, and have, after all these years, finally had a real chance to use your new ABS-Z.  It is incredible!  However, I have found my first issue.  executeAASkillOnChar  does not work for skills that have a speed unequal to zero, and so I cannot use it to have one sprite fire things like arrows at another sprite.  This activity works great as an ordinary skill accessed through q or through one of the numbers - I would just love it to work when one (non-actor) event attacks another event.  Thanks!

**Comment by KageDesu** [comment]
Hi. Projectile skill (with speed > 0) will be work by uAPI with next update. I added a new uAPI calls for this purposes. It's already implemented, but not published yet, still finishing update. Soon i will publish update.

**Comment by donaldderrick** [comment]
Hi Phoenix,

That is excellent news.  
I am so pleased with your ABS-Z tool - with this addition it will be my go-to for so many excellent map effects that will make the story of our game much more immersive)

(Note: I actually already have one game out, called Red Wolf, available on android, but that first one doesn't use an ABS as it was more of an adventure game.)
https://play.google.com/store/apps/details?id=com.horizons.redwolf&hl=en&gl=US￼
Red Wolf - Apps on Google Play
play.google.com

DD
