### ISSUE TITLE
Projectiles not showing when using MZ3D plugin

### ISSUE THREAD

**Issue by LoniMaple** [KageDesu/Alpha-ABS-Z#4]
Using the MZ3D plugin the projectile does not appear only the animation effect.
![Vídeo sem título ‐ Feito com o Clipchamp](https://github.com/KageDesu/Alpha-ABS-Z/assets/109419626/d297a39c-9b97-48e8-984e-18e2c0e01e4a)

**Comment by KageDesu** [comment]
Thank you for report this. This is a known problem. I haven't started work on adding compatibility between AABSZ and MZ3D plugins yet. Maybe in the future, right now I'm focused to finish all planned features on AABSZ itself.

**Comment by LoniMaple** [comment]
I am happy to know that.
